import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useDispatch, useSelector } from 'react-redux';
import { setUser, fetchContentAction } from '../services/store/reducers/testReducer'
import { getUser, getContent } from '../services/store/selectors/testReducer'

const Home: NextPage = () => {
  const { response: { username = '' } = {} } = useSelector(getUser);
  const { contents = [], isPending } = useSelector(getContent);
  const dispatch = useDispatch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Username: {username}
        </h1>

        <button onClick={() => dispatch(setUser({ username: `${Math.random()}`}))}>Click</button>
        <button onClick={() => dispatch(fetchContentAction())}>Get Content</button>

        <div className={styles.grid}>
          {
            !isPending && contents.length > 0 && contents.map((item: any, k: number) => (
              <div className={styles.card} key={k}>
                <h2>{item.name} &rarr;</h2>
                <p>{item.body}</p>
              </div>
            ))
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
